### ISSUE TITLE
[ SERVER ] request header 규칙 재정립 필요

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#102]
WEB 에서는, 

로그인 한 사람의 request header와 로그인 안된 사람의 request header의 field 가 다름
> 로그인 한 사용자 : ip + authorization
> 비로그인 사용자 : ip

헌데, findQuestionsBy_id request의 경우, authorization field 가 없으면 cors 에러가 발생
> 아마 spring 에서, 해당 field를 요구하기 때문
> 즉 비 로그인 사용자의 경우 게시물을 볼 수 없게 됨

그럼 비 로그인한 사람의 authorization field 를 null로 주면 되는것 아닌가?
> 물론 문자열 null만 줄 수 있음
> 아니면 'guest' 이런식의 문자열을 필드값으로 줄수는 있음
> 허나 현재 authorization값이 들어오면 Spring에서는,. 해당 필드값이 토큰이라고만 판단
> 유효성검사를 하게 되는데, 통과할리 없음
> request 실패 

제안 

1. authorization filed에 특정 문자열 "guest" 와 같은 문자열이 들어오면 유효성검사를 진행하지 마라.

**Comment by damin8** [comment]
- Main Server Filter 부분 (Http Filter)

![image](https://user-images.githubusercontent.com/52910837/82414835-9b627a80-9ab2-11ea-9043-6a9c57ece183.png)

- Token에 null or 공백 or guest라면, 토큰을 체크하지 않고 넘어가게 만들었습니다. (2020-05-20 15:59분 부로)

- 아직 서버 적용 전 로컬 테스트 후에 적용할 예정

**Comment by winterlood** [comment]
테스트 완료 및 이상 없으므로 이슈 종료합니다~
