### ISSUE TITLE
[ SERVER ] countallquestionbysearch 구현 및 findQuestionbyOption 형식 변환

### ISSUE THREAD

**Issue by hjg0629** [22hours/DevStudent#106]
원래는 Option에 맞추어 DB데이터를 가져오는 형식이었는데, 해당 방식은 실제 데이터가 많아지면 속도 및 효율성 저하 문제가 발생합니다.
예를들어 지금은 몇십개의 Question으로 테스트하였지만 만약 천만개의 Question중 like라는 단어가 제목이나 내용에 들어가 있는지 찾는다면 수 많은 사람들이 사용하기엔 적합하지 않은 방식이 되겠죠?

그렇기 때문에 기존 find로 검색하는 것이 아닌 MongoDB Index 기능을 공부하여 제목과 내용의 값들에 대해 색인을 추가하고자 합니다.

그렇게 한다면 성능면에서 훨씬 우수해 질것이라고 예상됩니다!

**Comment by hbin12212** [comment]
네!!! 감사합니다!!!

**Comment by hjg0629** [comment]
해당 파트 도입 완료되었고. 조금더 나은 처리를 위해 차후 튜닝작업을 해보겠습니다.
