### ISSUE TITLE
Double nickname check error

### ISSUE THREAD

**Issue by damin8** [22hours/DevStudent#119]
- 처음에 닉네임 검사 = 중복된 닉네임 확인 완료

![image](https://user-images.githubusercontent.com/52910837/84383343-12f57680-ac27-11ea-8853-9e5935daf80f.png)

- 두 번째 중복된 닉네임 확인 = 계속 로딩페이지에 대기 상태 (Error 부분)

![image](https://user-images.githubusercontent.com/52910837/84383316-083ae180-ac27-11ea-8aca-53a78993d80f.png)

**Comment by winterlood** [comment]
이미 해결된 이슈입니다.
해결 된 이슈는 확인 후 close 해주세요
