### ISSUE TITLE
[Image Server] 이미지 GET 실패

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#123]
사이트 내 결과 
![image](https://user-images.githubusercontent.com/46296754/85367830-fe897600-b564-11ea-94e8-17a6f20eca28.png)

GET 요청 결과
![image](https://user-images.githubusercontent.com/46296754/85367873-1103af80-b565-11ea-88a3-6453e18b5562.png)

**Comment by damin8** [comment]
- 실제로 파일들이 다 삭제 되어 있음.

![image](https://user-images.githubusercontent.com/52910837/85369934-f16e8600-b568-11ea-883e-3302e67d7822.png)

- 깜짝 놀라서 GCP Instance 로그 확인

![image](https://user-images.githubusercontent.com/52910837/85370035-1531cc00-b569-11ea-9c85-08e5170478f5.png)


빨간줄을 기점으로 삭제 되었음.

하지만, 프로그램 로직 상으로 삭제 한 것이 아님.

그리고 만약 삭제 되더라도 Dummy File만 조회 했기에 Dummy File만 삭제 되어야 하는데

Real File까지 삭제 되었음. 큰 문제라고 생각함.

예상 가는 문제점

1. GCP Storage의 **기본 세팅**이 3일 보관 후 알아서 삭제

2. Spring Server에서 삭제를 위해 Dummy Folder의 파일들을 가져온다.

가져 오고, 삭제 해야 하면 삭제

아니라면 가만히 냅둔다.

여기서 가만히 냅두는 곳에서 문제가 생기는 것인지..? (다시 Save를 시켜줘야 하나?)

일요일까지 해보고 다시 Issue에 댓글 남기겠습니다.

사용에 불편을 드려서 죄송합니다.

**Comment by damin8** [comment]
- 2020-07-02 목요일부로 테스트 완료

- GCP Storage에 있던 1일 보존 규칙 삭제 (default인 듯)

- 2020-06-29 부터 2020-07-02 까지 테스트 해본 결과 Dummy image는 삭제, Real image는 보존 되어 있는 것을 확인. (local, gcp 둘 다)
