### ISSUE TITLE
[ SERVER ] 로그인 후 Alarm 미발생 및 마이페이지 Alarm 미제공 문제

### ISSUE THREAD

**Issue by hjg0629** [22hours/DevStudent#124]
[ SERVER ] 로그인 후 Alarm 미발생 및 마이페이지 Alarm 미제공 문제
---

로그인을 하게 되면 미확인 알람들을 받아야 하지만 알람 Count 미제공 및 Slack에 에러가 계속 발생하는 문제가 생겼습니다.

![image](https://user-images.githubusercontent.com/46389195/86262231-925ce100-bbfa-11ea-9764-1a05c9d57d5d.png)

또한 MyPage에 들어갔을 때 해당 사용자의 알람을 모두 제공해주어야 하는데 아무런 값 없이 반환하는 경우가 발생하였습니다.

![image](https://user-images.githubusercontent.com/46389195/86262302-a86aa180-bbfa-11ea-9bd5-c2a9af346f15.png)

오류 탐색 결과 해당 문제는 사용자에게 할당되는 데이터라 내부적으로 토큰을 검사하다 보니 생기는 문제였습니다.
그 결과로 토큰만 검사하고 내부에 로직을 수행하지 않는 모습을 보여주고 있습니다.

![image](https://user-images.githubusercontent.com/46389195/86262528-f1baf100-bbfa-11ea-8902-614d75aacc03.png)

해당 문제점을 인지하였고 현재 작업은 완료된 상태입니다.
Security가 새롭게 적용된 점을 감안하여 다시 한번 모든 Logic에 대해서 예외적인 상황 테스트 진행 후 바로 적용 하겠습니다.

모두 죄송합니다.

**Comment by damin8** [comment]
확인이요 고생하셨습니다

내일 같이 이것저것 해봅시다

**Comment by winterlood** [comment]
👍 
적용 완료되고 문제 없으면 close 해주세요~~
수고하셨습니다 :D

**Comment by hbin12212** [comment]
확인했습니당 감사합니다
