### ISSUE TITLE
devlog 마크다운 문법 ## 만 인식 

### ISSUE THREAD

**Issue by jongwuner** [22hours/DevStudent#128]
![image](https://user-images.githubusercontent.com/16419202/87106355-3e0bce00-c298-11ea-9b40-efe377bffd72.png)

`##` 샵을 2개찍으면 목차에 콘텐츠가 생기지만

`#` 샵을 1개찍거나

`###` 샵을 3개찍으면 콘텐츠에 반영이 안되고 있는 현상

**Comment by winterlood** [comment]
### 문제 발생 사유 
현재, h2 (##)만을 대상으로 목차를 생성하여 그렇다.

### 제시 방향
h1은 대주제, h2은 중주제, h3는 소주제로 반영할 계획
빠르면 금일내에 처리가능

**Comment by winterlood** [comment]
https://github.com/22hours/DevStudent/issues/129 참고해주세요 
@jongwuner

**Comment by jongwuner** [comment]
@winterlood 확인완료데스네
