### ISSUE TITLE
devlog 목차와 사진 및 글이 overlay(겹치는 현상)

### ISSUE THREAD

**Issue by jongwuner** [22hours/DevStudent#129]
## 첫번째
![image](https://user-images.githubusercontent.com/16419202/87106660-e752c400-c298-11ea-8522-8b2ae74271a4.png)

## 두번째
![image](https://user-images.githubusercontent.com/16419202/87106719-02253880-c299-11ea-9f25-7d521602e2ee.png)

----------------------------

![image](https://user-images.githubusercontent.com/16419202/87106879-5e885800-c299-11ea-93b7-12933e497364.png)

글 영역, 목차 영역 div 배치

**Comment by winterlood** [comment]
😭  게시글을 크게 보여주려다 보니, 
화면을 줄였을 때, 목차가 게시글을 침범하는 현상이 발생하였습니다.

해당 문제는 UI구조의 개선을 통해 해결될 듯 합니다
7M3W spring에서 수행할 예정입니다 😄

**Comment by hbin12212** [comment]
😆수정했습니다

목차영역과 글영역을 분리해서 화면이 줄어들어도 겹치지 않게 하고, 글의 맨 아래에 있는 댓글 작성란까지 목차영역이 침범하지 않게 수정했습니다.

확인 후 이슈 닫아주세요👍

**Comment by winterlood** [comment]
> 😆수정했습니다
> 
> 목차영역과 글영역을 분리해서 화면이 줄어들어도 겹치지 않게 하고, 글의 맨 아래에 있는 댓글 작성란까지 목차영역이 침범하지 않게 수정했습니다.
> 
> 확인 후 이슈 닫아주세요👍

@jongwuner

**Comment by jongwuner** [comment]
넵넵넵 ! 확인하였습니다 너무 잘쓰고 있어요 감사합니다 효빈님
