### ISSUE TITLE
devlog에서 작성하는 게시글도 구글, 네이버에 노출되면 좋을 듯

### ISSUE THREAD

**Issue by jongwuner** [22hours/DevStudent#130]
## 네이버에 게시글 제목으로 검색
![image](https://user-images.githubusercontent.com/16419202/87115588-ae254e80-c2ae-11ea-942c-27cba70b7128.png)

## 게시글도 SEO 필요! 
![image](https://user-images.githubusercontent.com/16419202/87115615-bc736a80-c2ae-11ea-8c42-e6e77784731c.png)

**Comment by jongwuner** [comment]
`robot.txt` 랑 `sitemap.xml` 이 있나요 혹시?

**Comment by winterlood** [comment]
이미 작업중인 내용입니다.

**Comment by winterlood** [comment]
[Devstu RSS](http:api.devstu.co.kr/rss)
RSS가 2020-07-10부로 완성되었습니다 👍 
빠른시일내에 검색엔진에 등록될것입니다 
해당 이슈 close하도록 하겠습니다
> 문제 발생시 re-open해주세여
