### ISSUE TITLE
Devlog 모바일사이즈 뷰에서 컨트리뷰터 소개 div 사이즈 개선!

### ISSUE THREAD

**Issue by jongwuner** [22hours/DevStudent#131]
## 컨트리뷰터에 대한 div가 조금 더 넓어지면 보기 좋아질 것 같습니다!
![image](https://user-images.githubusercontent.com/16419202/87221960-e7db7f80-c3aa-11ea-870e-f29b50a6ac24.png)

-----
# feed와 동일한 너비를 가지면 딱 좋을 듯하오
![image](https://user-images.githubusercontent.com/16419202/87221987-296c2a80-c3ab-11ea-8eed-bcea8c4a552a.png)

# 배너 굿굿굿임
![image](https://user-images.githubusercontent.com/16419202/87221979-18bbb480-c3ab-11ea-8fc6-bdb2ac879ad2.png)

**Comment by winterlood** [comment]
👍 제보 감사드립니다

DEVLOG 페이지의 모바일 최적화가 아직 진행되지 않아서 그렇습니다 😭 
7M3W spring를 기약하고 있으며, 모바일 최적화 후 close하겠습니다

+ [QA] 라벨을 붙여 이슈오픈해주시면 감사드리겠습니다 😄

**Comment by winterlood** [comment]
![image](https://user-images.githubusercontent.com/46296754/87302940-42144600-c54d-11ea-8ee4-72163bb5ecdf.png)
Writer Box의 넓이를 조정했습니다

![image](https://user-images.githubusercontent.com/46296754/87302984-55bfac80-c54d-11ea-88ed-21e1aef01788.png)
이 부분에서, feed와 feed item의 너비가 같아지면 썸네일이 쪼그라들고.. 미관상 조금 그런것 같아서
둘의 의견의 중간점으로 feed 카피라이팅을 더 길게 수정할 예정입니다 😭

**Comment by winterlood** [comment]
@jongwuner  확인 후 직접 close 부탁드려요 😄

**Comment by jongwuner** [comment]
확인했고 잘 사용중이에요! 문닫겠습니다
