### ISSUE TITLE
[SERVER] Howto Question에 좋아요를 누를 수 없는 문제

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#132]
Request
![image](https://user-images.githubusercontent.com/46296754/87299417-efd02680-c546-11ea-9616-f1f15aa91311.png)

Response
![image](https://user-images.githubusercontent.com/46296754/87299371-d7f8a280-c546-11ea-8303-36dc07da3791.png)

**Comment by winterlood** [comment]
잘 눌립니다.

**Comment by hjg0629** [comment]
Refactoring 과정에서 반환값에 오류가 발생한 것( - Status : true로 반환됨에도 불구하고 mismatch라는 오류 형식을 반환한 문제.)
 + 
Answer에 좋아요를 했음에도 아예 반영이 안된 이유는 Answer에 좋아요를 찍고 Answer를 저장 안하는 문제가 발생하였음.( 기존 Embedded 형식을 유지하다보니 레거시가 남아 문제가 발생하였음)
