### ISSUE TITLE
[Image Sever] CORS 적용 후, image upload 안되는 문제

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#133]
![image](https://user-images.githubusercontent.com/46296754/87751487-0e7d3880-c839-11ea-958b-5c1244af86f3.png)

![image](https://user-images.githubusercontent.com/46296754/87751467-07562a80-c839-11ea-87b4-3b1bb8459af0.png)

nginx 와, spring controller에서 중복으로 
access-control-allow-origin : * 을 기입하여 발생한 문제로 확인 되었음

**Comment by winterlood** [comment]
현재, image server의 access-control-allow-origin 을 제거하여 업로드 중
문제가 해결되면 close 함

**Comment by damin8** [comment]
![image](https://user-images.githubusercontent.com/52910837/87751814-dcb8a180-c839-11ea-8295-274e0f7f0397.png)

![image](https://user-images.githubusercontent.com/52910837/87751826-e3dfaf80-c839-11ea-91f3-a89a07fbcac6.png)

- 썸네일 및 포스팅 이미지 잘 올라가는 것 확인

- 위의 이슈가 문제였음

- 확인 됐으니 이슈 close 하겠습니다
