### ISSUE TITLE
[QA] image server 마비시, devlog post를 작성조차 할 수 없게 되는 것에 대하여

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#134]
현재 devlog post는, 
정해진 item의 layout에 맞춰지게 하기 위하여,
thumbnail 이미지를 업로드 하게 끔 강제하고 있음,

따라서 ,이것에 대한 대처방안을 고려해볼 필요가 있음

**Comment by winterlood** [comment]
--------------------- 여기서부터 토론 시작 ------------------------------------

**Comment by jongwuner** [comment]
Default 썸네일을 DEVSTU 로고로 하면 좋을 것 같다는 생각입니다. 혹은 정보기여자의 프사?

**Comment by winterlood** [comment]
> Default 썸네일을 DEVSTU 로고로 하면 좋을 것 같다는 생각입니다. 혹은 정보기여자의 프사?

의견 감사합니다 😄 
만들어보고 여기 올려보겠습니다
예상되는 시기는 다음주 쯤이 될 것 같군여,

**Comment by hbin12212** [comment]
썸네일을 등록하지 않고 글을 저장하게되면 **default 이미지**로 썸네일이 등록되는 것으로 변경했습니다!!

**Comment by winterlood** [comment]
확인하였습니다
문제가 발생할 시 다시 re-open 합니다
@sg05138  고생했습니다 😶
