### ISSUE TITLE
[QA] devlog 게시글 임시저장 조건을 수정 할 필요가 있을듯 하다.

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#135]
현재, devlog는 
제목, 태그, 본문을 반드시 특정 길이 이상을 작성하여야만, 출간 할 수 있도록 설계되어있다
이 때 임시저장 조건과 출간 조건이 똑같아서, 임시저장에 불편함이 있을 수 있음
따라서, 임시저장 조건에 대해한 의견 필요

**Comment by jongwuner** [comment]
동의합니다 !! 의견 반영해주셔서 고마워요~!

**Comment by hbin12212** [comment]
Devlog 글 작성 시 임시저장은 본문을 20글자 이상 작성 하게 되면 바로 작동하는 것으로 변경했습니다!!!

**Comment by winterlood** [comment]
확인했습니다
해당 issue는 문제시 다시 re-open 합니다
@sg05138
