### ISSUE TITLE
7월 4주차 Sprint 안건

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#136]
![image](https://user-images.githubusercontent.com/46296754/87786701-60dc4a80-c875-11ea-823a-f54176ed73f1.png)

## 1. DEVLOG 와 그 외의 미비된 알람 기능
![image](https://user-images.githubusercontent.com/46296754/87786973-d6e0b180-c875-11ea-86bc-9f70ea086f7e.png)

- devlog comment 생성될 시 글 작성자에게 알람
- devlog re-comment 생성 될 시, 글 작성자와 comment author에게 알람
- howto like 시, question 혹은 answer 작성자에게 알람
- howto comment 시, question 혹은 answer 작성자에게 알람
- howto adopt 시, answer 작성자에게 알람

모든 알람기능은 sender와 receiver로 구성 된다   
> Ex) 이정환님이 하정구님의 글에 좋아요 했습니다  
> 여기서 sender=이정환, receiver=하정구 이다.  
이 때 sender == receiver의 조건이 성립 할 시 알람을 생성하지 않는다.

## 2. USER 비밀번호 찾기

설계부터 시작해야 함

## 3. USER EVENT HISTORY 기록하기

벤치마킹 : https://api.github.com/users/winterlood/events 

## 4. [UX] : devlog new post 임시저장 기능 보완하기
#135 참고

## 5. [UX+OPS] : Google Adsense 위치 조정 및 광고 최적화

현재 문제점
- 광고 호출수 대비 노출률이 너무 낮다
- 관련없는 카테고리 광고 차지율 30%
- 클릭 비율이 매우 낮다, 즉 매력있고, 합당한 광고 노출 UX고려

**Comment by winterlood** [comment]
- 설명이 미비한 점 or
- 토론이 필요한 점 or 
- 추가되었으면 좋겠는 점 or 
- 삭제하고 싶은 점 

모두 #136번 현재 issue에서 토론하도록 하겠습니다! 

**이 토론은 2020-07-20 00시에 종료됩니다.**

============== 토론 시 작 ==================

**Comment by damin8** [comment]
### 1. DEVLOG 와 그 외의 미비된 알람 기능

- devlog re-comment 생성 될 시, 글 작성자와 comment author에게 알람

이전에 re-comment는 글 작성자에게 알람이 안가도 될 거 같다고 했는데, 생각을 곱씹어보니 알람이 가도 괜찮을 듯 하다

단, comment author == 글 작성자라면 알람 1개만 가도록 하자.

### 2. USER 비밀번호 찾기

시퀀스 다이어그램을 한 번 그려봤습니다

![image](https://user-images.githubusercontent.com/52910837/87847663-f4188d00-c914-11ea-831c-3585c2d7d9f8.png)

### 3. USER EVENT HISTORY 기록하기

개인적인 바람으로는 본격 런칭? 전에 구축을 하고 싶지만 여건 상 쉽지 않다 (할게 좀 많은 느낌이 안 없어진다).

따라서 이 이벤트는 차차 넓혀가면서 생각해보는 것도 나쁘진 않을 거 같다.

### 4. [UX] : devlog new post 임시저장 기능 보완하기

임시저장 같은 부분은 지금 client-side 에서 관리하고 있다.

만약 server-side에서 관리한다면 로그아웃, 웹 브라우저 닫기, 시간이 많이 지난 뒤 등등의 이벤트가 일어나더라도 임시 저장이 되지 않을까?

devlog 같은 경우는 사용자의 정말 소중한 자산이기 때문에 server-side에서 관리하는 것도 괜찮을 듯 하다.

물론, 위의 로그아웃, 웹 브라우저 닫기, 시간이 많이 지난 뒤 등등의 이벤트가 해결되지 않을 수도 있다.

### 5. [UX+OPS] : Google Adsense 위치 조정 및 광고 최적화

우리가 앞서 끝내야 할 작업들을 끝낸 후에 사용자들을 유치하면서 병행해도 될 듯 하다.

나는 개인적으로 현재 시점에서는 dev가 더 우선순위가 있다고 생각한다.

**Comment by hjg0629** [comment]
1. DEVLOG 와 그 외의 미비된 알람 기능
devlog comment 생성될 시 글 작성자에게 알람( 동의 )
devlog re-comment 생성 될 시, 글 작성자와 comment author에게 알람( 동의 )
howto like 시, question 혹은 answer 작성자에게 알람
( 이거는 필요할 지는 의문. 너무 많은 알람은 사용자가 보기에 좋지 않을 수 있음. )
howto comment 시, question 혹은 answer 작성자에게 알람( 동의 )
howto adopt 시, answer 작성자에게 알람( 동의 )

답글과 댓글, 채택에는 알람이 필요하지만
게시글에 좋아요까지 추가하는건 괜찮을까?


2. USER 비밀번호 찾기
이메일 입력.

분기
 - DB내에 계정이 존재하면 토큰 발송
 - 일단 해당 이메일로 검증 토큰 발송( 이메일 인증과 같겠쥬 )

사용자가 받은 이메일로 링크타고 와서 인증하면 재발급 요청!
이때 BackEnd에서는 비밀번호 변경 요청이 들어왔다는 것을 계정에 기록해야함
( 악용 방지를 위하여 - 토큰 검증이 없기 때문에 누구든지 접근 가능. )


3. USER EVENT HISTORY 기록하기
사용자의 Activity에 대한 기록은 남기는게 좋다.

4. [UX] : devlog new post 임시저장 기능 보완하기
Front에서 가지는 조건을 없애고 Back에서 Flag를 가지고 임시저장 글과 출간된 글을 구분하는 것도 하나의 방법이라고 생각함.

5. [UX+OPS] : Google Adsense 위치 조정 및 광고 최적화
이거는 아직 모르겠
