### ISSUE TITLE
findAllUserInfo가 정상적인 값을 반환하지 않음

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#138]
![image](https://user-images.githubusercontent.com/46296754/88018606-0851c980-cb63-11ea-8a62-de704638f583.png)
호출시, 정상적으로 무언가를 반환하긴 함

![image](https://user-images.githubusercontent.com/46296754/88018641-1dc6f380-cb63-11ea-9870-8a017bc10907.png)
현재 status:true 라고 반환됨

![image](https://user-images.githubusercontent.com/46296754/88018676-29b2b580-cb63-11ea-8abd-e6696e13f0f0.png)
원래는 user들의 정보를 Array로 반환해야함

잘되다가 안되는걸 보니, 무언가 리팩터과정에서 발생한 문제로 의심된다

**Comment by damin8** [comment]
Issue 확인했고

어느 부분에서 문제인지 파악되면 바로 comment 와 같이 update 할게요

지금 밖이라서 들어가는 대로 확인하겠습니다

**Comment by damin8** [comment]
2020-07-21 18시 03분

- 확인 결과 원래 반환을 하던 object를 status : true로 변경했다.

- 리팩터 과정에서 발생한 문제가 맞다.

- 2020-07-21 18:06 부로 서버 업데이트

**Comment by winterlood** [comment]
확인되었습니다
@damin8  조속한 조치 감사해요 😁
