### ISSUE TITLE
Howto comment request 전송 시, CORS에러 발생

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#139]
Request 는 다음과 같다.
![image](https://user-images.githubusercontent.com/46296754/88252444-20ebec00-cce9-11ea-8f48-2803866a734e.png)

Response는 다음과 같다.
![image](https://user-images.githubusercontent.com/46296754/88252454-2ea17180-cce9-11ea-9d10-300a9b522f3d.png)

이 또한, 리팩터링 과정을 거치며 발생한 문제일 것으로 염려가 된다.

**Comment by damin8** [comment]
- 2020-07-23 13시 47분 확인 했습니다.

- 확인 후에 문제 원인, 해결 유무를 comment로 남기겠습니다.

**Comment by damin8** [comment]
- 2020-07-23 14시 25분  

- war 파일이 2개가 동시에 올라가서 에러가 난 듯 합니다. (v0.8.1, v0.8.2)

- 1개를 끈 후 테스트 해보니 정상적으로 작동되는 것 확인했습니다.

![image](https://user-images.githubusercontent.com/52910837/88254436-4cbea000-ccf0-11ea-9fea-5cb10c572634.png)

**Comment by hjg0629** [comment]
왜 2개켜진건지 이유를 모르겠네...

**Comment by hbin12212** [comment]
확인했습니당 👯
