### ISSUE TITLE
모바일 환경에서 작성날짜(Date) 가 Nan으로 표기 되는 문제

### ISSUE THREAD

**Issue by damin8** [22hours/DevStudent#140]
- 모바일 환경에서 nan으로 표기가 된다.

- 하지만, PC에서는 잘 보인다.

- 하단에 사진 첨부

---

## 모바일 (IOS) 환경

> 브라우저는 슬랙 브라우저 활용

- Question 사진

![image](https://user-images.githubusercontent.com/52910837/88445145-c8892b80-ce5b-11ea-83ee-b3e23ddf20e7.png)

- Answer 및 Comment 사진

![image](https://user-images.githubusercontent.com/52910837/88445156-d76fde00-ce5b-11ea-9ca2-58bc145e0b2d.png)

## PC (Windows) 환경

> 브라우저는 Chrome 브라우저 활용

- Question 사진

![image](https://user-images.githubusercontent.com/52910837/88445161-ea82ae00-ce5b-11ea-9a6d-befd914aedc1.png)

- Answer 및 Comment 사진

![image](https://user-images.githubusercontent.com/52910837/88445175-fec6ab00-ce5b-11ea-81b1-93edcce81190.png)

**Comment by winterlood** [comment]
해당 문제는 IOS, slack browser 환경에서 식별되었습니다!
최대한 빠르게 조치하도록 하겠습니다 
이슈 감사드립니다 👍

**Comment by winterlood** [comment]
![image](https://user-images.githubusercontent.com/46296754/88655432-b3d1bf80-d109-11ea-9b84-eb1466473c19.png)

완벽한 해결은 못 되었지만,
isNaN 함수를 통하여 적어도 NaN값은 반환되지 않도록 처리하였습니다
확인 부탁드려도 될까요 ?? 😊

**Comment by damin8** [comment]
- 2020-07-31 16:46 부로 정상 작동 되는거 확인했습니다.
