### ISSUE TITLE
모바일 (IOS) 웹 브라우저 (Safari) 에서 무한 로딩 현상

### ISSUE THREAD

**Issue by damin8** [22hours/DevStudent#141]
- PC에서는 잘 되는 Devstu

- Mobile (IOS) 웹 브라우저 (Safari) 에서는 무한 로딩 현상이 일어난다.

---

## PC (Windows) 웹 브라우저 (Chrome)

> 2020-07-25 10시 05분 부 사진 촬영

![image](https://user-images.githubusercontent.com/52910837/88445586-988f5780-ce5e-11ea-98d3-5c3ef25d34dd.png)

## Mobile (IOS) 웹 브라우저 (Safari)

> 2020-07-25 10시 02분 부 사진 촬영

![image](https://user-images.githubusercontent.com/52910837/88445604-b361cc00-ce5e-11ea-8827-b15d591a0f0f.png)

![image](https://user-images.githubusercontent.com/52910837/88445607-b65cbc80-ce5e-11ea-94b6-b6a258e9b630.png)

## Server 의 로그

![image](https://user-images.githubusercontent.com/52910837/88445662-f9b72b00-ce5e-11ea-9708-807be6885089.png)

---

- 혹시 네트워크 문제일까 해서 다른 웹 사이트 (github, google, naver) 등등 들어가면 잘 들어가진다.

- 혹시 그래도 네트워크 문제일까 해서 2분정도 home 에서 기다려봤지만 무한 대기 상태

- 토큰 변조로 로그가 찍히는거 봐서는 Mobile 에서는 Token 값이 이상하게 잡히나? (잘 모르겠다..)

**Comment by damin8** [comment]
- 이전 로그인 되어 있는 상황 때문에 그랬던 것이다.

- 로그아웃 후 다시 로그인 하니 정상적으로 작동

**Comment by winterlood** [comment]
다행이다 😔
