### ISSUE TITLE
모바일 햄버거 메뉴 오탈자

### ISSUE THREAD

**Issue by 0916dhkim** [22hours/DevStudent#144]
![Capture](https://user-images.githubusercontent.com/8978815/88645891-9861b700-d0ff-11ea-8b71-79d8a9415f07.PNG)
로그인 하지 않은 상태에서 모바일 햄버거 메뉴에 오탈자가 있습니다.
~~Knoledge~~ -> Knowledge.

그리고 "모든 것을 공유합니다"의 번역은 "We share everything" 으로, 혹은 "자유로운 지식공유"의 의도라면 "Freedom of knowledge sharing" 으로 하는 것을 제안합니다.

한국인을 대상으로 하는 서비스니까 영어 번역은 삭제하는것도 방법일 것 같습니다.

**Comment by winterlood** [comment]
![image](https://user-images.githubusercontent.com/46296754/88654768-c8618800-d108-11ea-98ba-04d158997818.png)

저의 짧은 영어실력을 조금이라도 빠르게 감출수 있게 해주셔서 감사드립니다 !!.. 🤣
추가로, 한국인 대상서비스인데, 영어가 써져있는 점이 제가 생각해도 이상하더라구요
그래서 과감히 영어를 배제하고 한국말로 다시 적어놓았습니다.

저희 DEVSTU에 많은 관심 가져주셔서 정말 감사드려요 😆😆

**Comment by 0916dhkim** [comment]
@winterlood 문구가 더 멋있어진것 같습니다. 이슈는 닫아주세요 👍
