### ISSUE TITLE
Script API Key 노출

### ISSUE THREAD

**Issue by gwangun-kim-switchwon** [22hours/DevStudent#147]
index.html 일 듯 보이는데 해당 페이지에서 Firebase 관련 var init 부분에서 devstu 관련 Firebase API Key, Project ID 등 중요한 요소들이 노출이 되어 있는데, 해당 Script 부분 서버로 빼서 index.html에서 load 하는 방식으로 바꾸면 어떨까 합니다.

**Comment by winterlood** [comment]
보안이슈 지적에 감사드립니다 :D
본 repos는 앞으로 devstu의 open source 프로젝트와 공식창구를 위해 사용될 예정이므로 
프로젝트 코드를 본 repos에서 제거하는 것으로 결정하였습니다. 
해당 firebase api key와 project id는 안전을 위해 폐기하고 다시 발급받아 사용중입니다
