### ISSUE TITLE
[ SERVER ] Alarm ~/main/alarm/count/all total값 반환 오류

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#151]
### Request Body
![image](https://user-images.githubusercontent.com/46296754/94141690-1a741f00-fea8-11ea-88f1-dbd58269001f.png)

### Response Body
![image](https://user-images.githubusercontent.com/46296754/94141717-2364f080-fea8-11ea-8812-412a8f0ae934.png)

total값 전달에 오류가있음
> total = read + known이 성립하지 않음

**Comment by damin8** [comment]
2020-09-28 BUG FIX

![image](https://user-images.githubusercontent.com/52910837/94544116-d016e780-0285-11eb-9208-b4552b60adbc.png)
