### ISSUE TITLE
마이페이지에서 이용자명, 소속 등이 제대로 표출되지 않음

### ISSUE THREAD

**Issue by dokdo2013** [22hours/DevStudent#155]
- 마이페이지에서 이용자명, 소속, 메시지, 포인트 등이 제대로 출력되지 않음.
- 데스크톱 모바일 모두 동일한 증상입니다.
- 크롬(version 86, windows 10), 크롬 안드로이드(version 86, android 10)에서 확인되었습니다.

![image](https://user-images.githubusercontent.com/22076477/98508173-620d0980-22a2-11eb-872f-042f7e06da38.png)
![image](https://user-images.githubusercontent.com/22076477/98508229-7b15ba80-22a2-11eb-8bef-dde9589e68f2.png)

**Comment by winterlood** [comment]
#156 해결되었습니다.
