### ISSUE TITLE
마이페이지에서 탭간 이동시 userinfo가 null 또는 undefined로 넘어감

### ISSUE THREAD

**Issue by dokdo2013** [22hours/DevStudent#156]
### 최초 마이페이지 접속시
- total, activity, devlog 탭 선택시 각각 userinfo가 'null'인 상태로 넘어감

### userinfo/null 로 넘어간 이후
- userinfo가 null일 경우 탭 선택시 userinfo가 undefined로 넘어감

## 현상 캡쳐
- (1) 마이페이지 최초 접속
![image](https://user-images.githubusercontent.com/22076477/98508930-b06ed800-22a3-11eb-83fe-b847cbac718c.png)
- (2) activity 탭 클릭시
![image](https://user-images.githubusercontent.com/22076477/98508968-bfee2100-22a3-11eb-8129-e024d895de79.png)
- (3) devlog 탭 클릭시
![image](https://user-images.githubusercontent.com/22076477/98509001-d1372d80-22a3-11eb-95b1-8e5d86f397bd.png)

- (1),(2),(3)은 순차실행한 결과임.

**Comment by winterlood** [comment]
이슈 제보 감사합니다
현재 Server Response 관련 문제가 발생하여 원인 식별중에 있습니다

**Comment by winterlood** [comment]
![image](https://user-images.githubusercontent.com/46296754/98510523-9edaff80-22a6-11eb-8cf8-ecdb6cfbc9a5.png)

2020-11-08, 16:14부로 정상화 되었습니다 👍
