### ISSUE TITLE
devlog 피드의 게시물을 클릭하여도 열람이 되지 않음.

### ISSUE THREAD

**Issue by dokdo2013** [22hours/DevStudent#157]
1. devlog 피드 영역의 게시물을 클릭하여도 로딩만 돌아가면서 열람이 되지 않습니다.
![image](https://user-images.githubusercontent.com/22076477/100688212-2b1fa480-33c5-11eb-8b81-6c95432add5a.png)

2. HTML title에 **undefined's log - undefined** 라고 뜹니다.
![image](https://user-images.githubusercontent.com/22076477/100688270-52767180-33c5-11eb-9312-a66dc5c3f598.png)

**Comment by winterlood** [comment]
제보 감사합니다 원인 파악 후 조치하도록 하겠습니다 👍

**Comment by damin8** [comment]
제보 감사드립니다 !

- 2020-12-08 14:49 부로 에러 해결 됐습니다 !

- 확인 되시면, issue close 부탁드립니다 :D

![image](https://user-images.githubusercontent.com/52910837/101445283-912b9f00-3964-11eb-9e63-0fc73e6310fd.png)

**Comment by dokdo2013** [comment]
확인했습니다~ issue close 하겠습니다
