### ISSUE TITLE
[Back end] createComment중 Token이 갑자기 만료되는 경우 

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#16]
![image](https://user-images.githubusercontent.com/46296754/78790903-23506180-79ea-11ea-9e53-ff67e348c5ad.png)

정상적인 로그인 절차를 거쳐 발급받은 토큰인데,

되다가 안됨..

**Comment by damin8** [comment]
음... 누가 로그인을 해서 그런가?

저 코멘트를 작성할 때 누가 로그인하면 token이 바껴서 그런건가?

되다가 안되는거는 진짜 애매하네

로그좀 확인해볼게

**Comment by damin8** [comment]
일단 aaa는 token이 **im7ytgvIr4a7SSroMk1H** 로 되어 있음.

이 부분 만약 누가 로그인해서 바뀐게 아니라면 자세히 봐야하는 문제일 듯

**Comment by winterlood** [comment]
@damin8  토큰이 잘못 된 것 ?

**Comment by damin8** [comment]
토큰이 위에 사진에 나와있는 거랑 다른데

db에 저장되어 있는 값은 **im7ytgvIr4a7SSroMk1H** 임

예상되는 문제점은

1. server 내부적으로 token 발급이 잘못되었다

2. 누군가가 로그인을 해서 token 값이 바꼈다

이 둘 중 하나일 듯

**Comment by winterlood** [comment]
2번일 가능성이 크다고 보는데 ...

**Comment by damin8** [comment]
- 로그인 구조 변경
