### ISSUE TITLE
[Back End] Comment달기 시 Question에 대한 comment는 Answer id로 줘야 하는지??

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#17]
제곧내

**Comment by damin8** [comment]
내가 이해한 이슈가 맞는지 확인 바람 

Question에 comment를 달기 위해서는 answer _id 어떤 걸로 줘야 하는지 물어보는거?

@winterlood

**Comment by winterlood** [comment]
yes

**Comment by damin8** [comment]
![image](https://user-images.githubusercontent.com/52910837/78793408-56482480-79ed-11ea-904e-58976967f9e0.png)

Description에 있슴돠

**Comment by winterlood** [comment]
ㅈㅅ합니다
