### ISSUE TITLE
New Question 이미지 업로드 구조

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#38]
본 이슈는 이미지 시스템이 구축 된 뒤 close 합니다

## 방법 1. 
**프록시를 거쳐가는** 이미지 서버를 사용한다.
> 모든 데이터의 엔드포인트를 통일한다

#### 업로드 
![image](https://user-images.githubusercontent.com/46296754/80487929-8bb2b300-8998-11ea-9e72-f79031fd65b0.png)

#### 다운로드
![image](https://user-images.githubusercontent.com/46296754/80488041-b8ff6100-8998-11ea-95bf-61690510810b.png)

## 방법 2. 
**프록시를 거치지 않는** 이미지 서버를 사용한다.
> 프록시 서버는 이미지에 관련하지 않는다.

#### 업로드
![image](https://user-images.githubusercontent.com/46296754/80488181-e946ff80-8998-11ea-99d1-783b62953ff8.png)

#### 다운로드
![image](https://user-images.githubusercontent.com/46296754/80488211-f237d100-8998-11ea-9c4a-1c54db2a7786.png)

**Comment by damin8** [comment]
굉장히 중요한 논제인거 같네

이것도 얘기해봐야 할 거 같음

- preview image를 web browser에 저장해놓고, 게시글 저장 혹은 등등의 기능으로 확실하게 저장할 때 Server에게 전달

- preview image를 바로 spring server에 저장시켜놓고, get url 을 받아서 띄우느냐

**Comment by damin8** [comment]
- graphql에서 image 송 수신이 어떤지를 아예 몰라서 research를 좀 해봐야 할 거 같다.

- 만약, graphql에서 image 송 수신이 원활하게 이루어진디면 나는 1번이 굉장히 괜찮다고 생각

- 아니라면, 2번으로

- 이거는 research가 필요하다 @hjg0629

**Comment by winterlood** [comment]
의견감사 내일 논의해보도록 합시다잉

**Comment by damin8** [comment]
![image](https://user-images.githubusercontent.com/52910837/80704715-0a862800-8b20-11ea-9803-96c3d29e190f.png)


- 아키텍처

**Comment by damin8** [comment]
- 이미지 서버 구축 완료

- upload, download 테스트 완료

- dummy, real data 구분 완료

- 구축 완료 되었기에 close 하겠습니다.

**Comment by winterlood** [comment]
S3로 대체
