### ISSUE TITLE
2020-04-30 Damin's FeedBack (React)

### ISSUE THREAD

**Issue by damin8** [22hours/DevStudent#40]
- 이메일 버튼 선택 후, Focus? 주변에 파란색이 남아 있는 상태

![image](https://user-images.githubusercontent.com/52910837/80705467-73ba6b00-8b21-11ea-8285-d44ef6d51791.png)

- 닉네임, 이메일 등등 입력하는 칸 너무 넓은 것 같다 (페이지 풀 스크린 기준)

- 닉네임 설정 후에, 다시 로그인 하는거 조금 아쉽다

---

- 님이 아이콘? 옆에 있었으면 좋겠다

![image](https://user-images.githubusercontent.com/52910837/80707793-833bb300-8b25-11ea-986e-dde00acb8889.png)

---

- 클릭했을 때 border? 없는게 나을수도 있을거 같다

![image](https://user-images.githubusercontent.com/52910837/80707836-98b0dd00-8b25-11ea-920e-cb6338892d84.png)

---

- 미리 보기 설정을 서버쪽에서 바꿔야 할 듯?

![image](https://user-images.githubusercontent.com/52910837/80708077-ff35fb00-8b25-11ea-8337-2ef2b481f71f.png)
![image](https://user-images.githubusercontent.com/52910837/80708187-34424d80-8b26-11ea-8e8b-b147ff4ab237.png)

---

- 핫 게시물 위로 올리는 것도 좋을 거 같다

![image](https://user-images.githubusercontent.com/52910837/80708136-1d036000-8b26-11ea-8002-62352c06f013.png)

---

- footer 깨지는 현상?

![image](https://user-images.githubusercontent.com/52910837/80708222-445a2d00-8b26-11ea-96ae-211dff68b574.png)

**Comment by hbin12212** [comment]
로그인 | 회원가입 버튼이랑 로그인했을 때 나오는 닉네임 버튼 수정했습니다.

**Comment by damin8** [comment]
- 모든 사항 커뮤니케이션 완료

- 수정 된 것들 확인
