### ISSUE TITLE
1차 QA

### ISSUE THREAD

**Issue by damin8** [22hours/DevStudent#47]
Spring

1. 로그인 시점 앞당기기
2. 좋아요 or 싫어요 undefined
3. comment undefined
4. hot 게시물 view 생각하기
5. c# -> c_sharp로 바꾸기

React

1. image 없을때는 요청 안하기
2. QA Box handle adopt에 author nickname이 글쓴이로 와야 함.
3. 등급 점수 바꾸기
4. 깃허브 icon 클릭 시, 콜론 없어짐

**Comment by hbin12212** [comment]
4번 해결했어용

**Comment by winterlood** [comment]
넹넹구링
