### ISSUE TITLE
[SERVER] Mypage에서 Gitlink 설정 후, 로그아웃 후 로그인 시 리턴되는 user 객체의 gitLink 누락 문제

### ISSUE THREAD

**Issue by sg05138** [22hours/DevStudent#48]
![image](https://user-images.githubusercontent.com/52522662/81254450-0b5e1300-9066-11ea-9c9c-3d97b55a97fb.png)

login 후 받은 user객체
잘보면 gitLink 가 null 로 옴

**Comment by damin8** [comment]
- 서버 로직 변경

- test완료.

- close 하겠습니다.
