### ISSUE TITLE
[React] Comment 달면 nickname, grade 등등 (UserInfo)가 안보이는 상태

### ISSUE THREAD

**Issue by damin8** [22hours/DevStudent#49]
![image](https://user-images.githubusercontent.com/52910837/81273937-951fd780-908a-11ea-821e-299eda9a5f8e.png)

- comment 달면, 누가 달았는지 나오지 않는다.

![image](https://user-images.githubusercontent.com/52910837/81274114-d617ec00-908a-11ea-9a0e-71334174a023.png)

- 받은 값

**Comment by hbin12212** [comment]
해결했어용
이제 닉네임 보이고 닉네임 누르면 /userinfo로 갑니다요~
