### ISSUE TITLE
[React] HowTo게시판, 게시글 내 Comment 글의 길이 초과로 오른쪽 영역 벗어나는 BUG

### ISSUE THREAD

**Issue by hjg0629** [22hours/DevStudent#51]
![zzc](https://user-images.githubusercontent.com/46389195/81283486-b3d89b00-9097-11ea-8235-46a5c566bd0d.JPG)

**Comment by hbin12212** [comment]
![image](https://user-images.githubusercontent.com/52522662/81560353-37fa8d80-93cc-11ea-82dc-d0eb53daabe3.png)

수정했습니다!!!
