### ISSUE TITLE
[React] CreateQuestion 에서 tag 작성할때 잘리는 현상

### ISSUE THREAD

**Issue by damin8** [22hours/DevStudent#52]
- createQuestion 에서 tag 작성할때 잘리는 현상

![image](https://user-images.githubusercontent.com/52910837/81283574-d5398700-9097-11ea-9cff-6ad7db164206.png)

**Comment by winterlood** [comment]
![image](https://user-images.githubusercontent.com/46296754/81902047-78d7e980-95fa-11ea-96f0-e170af468d70.png)

Tag input의 위치가 적절하지 못해서 발생한 문제

Thanks to Good Issue!  @damin8
