### ISSUE TITLE
[React] 홈페이지 회원 등급 점수 기준과 구글 docs 회원 등급 점수 기준 불일치

### ISSUE THREAD

**Issue by damin8** [22hours/DevStudent#56]
- 홈페이지 회원 등급 점수 기준

![image](https://user-images.githubusercontent.com/52910837/81526434-8be88080-9392-11ea-9cba-b2d1de5e6c30.png)

- 구글 docs 회원 등급 점수 기준

![image](https://user-images.githubusercontent.com/52910837/81526415-7e32fb00-9392-11ea-874a-080930b5380f.png)

- 어느 것으로 할 건지 선택도 가능할 듯

- 개인적으로 홈페이지 회원 등급 점수가 나은듯. (아래는 너무 빨리 올라가는 듯 하다)

**Comment by hbin12212** [comment]
이거 해결은 했는데 원래꺼가 더 좋으면 다시 바꿀게용
