### ISSUE TITLE
[Spring] createQuestion -> findAllQuestion Error

### ISSUE THREAD

**Issue by winterlood** [22hours/DevStudent#6]
![image](https://user-images.githubusercontent.com/46296754/78643658-8a3d2000-78ef-11ea-9bde-d6ed712ce783.png)

![image](https://user-images.githubusercontent.com/46296754/78643668-90cb9780-78ef-11ea-8d01-7705ca00b639.png)

![image](https://user-images.githubusercontent.com/46296754/78643706-9f19b380-78ef-11ea-9910-ea36a9ae24e8.png)

![image](https://user-images.githubusercontent.com/46296754/78643723-a93bb200-78ef-11ea-8083-38844ecbcbb2.png)

![image](https://user-images.githubusercontent.com/46296754/78643791-ca040780-78ef-11ea-8e39-0e627785087a.png)

게시글 저장 안됨

**Comment by winterlood** [comment]
@damin8  @hjg0629

**Comment by damin8** [comment]
![image](https://user-images.githubusercontent.com/52910837/78682076-824da200-7928-11ea-955d-f2d6c3c0dcd2.png)

![image](https://user-images.githubusercontent.com/52910837/78682104-8aa5dd00-7928-11ea-9a29-a336823e4a62.png)

![image](https://user-images.githubusercontent.com/52910837/78682138-95f90880-7928-11ea-8c9f-26fecbdd6193.png)

![image](https://user-images.githubusercontent.com/52910837/78682194-a4dfbb00-7928-11ea-92e2-ce7e25ee16f2.png)

- postman으로 실행해봤을 때 데이터 잘 들어갑니다

- null 값 온거면 token이 안 맞았을 수도 있어요!

- @winterlood

**Comment by damin8** [comment]
확인되면 issue close 하겠습니다

**Comment by winterlood** [comment]
![image](https://user-images.githubusercontent.com/46296754/78685102-3dc40580-792c-11ea-8f14-9d82d75994f3.png)

다음과 같은 mutation에서도 오류발생

> 혹시 token 확인에서 문제가 있는건가??

**Comment by winterlood** [comment]
nickname이 중복된게 있어서 오류가 난거였음 
배포단계에서는 문제없음
