### ISSUE TITLE
[React] HowTo 게시글에 태그 길이가 길고 창 사이즈 조금만 줄이면 태그가 잘리는 Issue

### ISSUE THREAD

**Issue by hjg0629** [22hours/DevStudent#75]
태그 6개이고 길이가 길다보니 창 크기가 조절되면 잘리는 문제가 발생하였습니다.

![image](https://user-images.githubusercontent.com/46389195/81559896-41372a80-93cb-11ea-97e7-fec847caff03.png)

**Comment by winterlood** [comment]
tablet view를 제작하여 해결하였음
